package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mikiobraun/dev-router/internal/config"
	"github.com/mikiobraun/dev-router/internal/scanner"
)

func Generate(cfg *config.Config, projects []scanner.Project) string {
	var sb strings.Builder

	sb.WriteString("# Generated by dev-router - do not edit manually\n\n")

	for _, p := range projects {
		if !p.Enabled {
			continue
		}

		subdomain := fmt.Sprintf("%s.%s", p.Name, cfg.Domain)

		sb.WriteString(fmt.Sprintf("%s {\n", subdomain))
		sb.WriteString(fmt.Sprintf("\ttls %s %s\n", cfg.CertPath, cfg.KeyPath))

		if p.Auth && cfg.AuthUpstream != "" {
			// OAuth discovery must be public (not gated), and it identifies the
			// resource by this host — route it to the auth service.
			sb.WriteString("\thandle /.well-known/oauth-protected-resource {\n")
			sb.WriteString(fmt.Sprintf("\t\treverse_proxy %s\n", cfg.AuthUpstream))
			sb.WriteString("\t}\n")
			// Everything else is gated: forward_auth validates, then we proxy.
			sb.WriteString("\thandle {\n")
			sb.WriteString(fmt.Sprintf("\t\tforward_auth %s {\n", cfg.AuthUpstream))
			sb.WriteString("\t\t\turi /verify\n")
			sb.WriteString("\t\t\tcopy_headers X-Volume-User X-Volume-Scopes\n")
			sb.WriteString("\t\t}\n")
			sb.WriteString(fmt.Sprintf("\t\treverse_proxy localhost:%d\n", p.Port))
			sb.WriteString("\t}\n")
		} else {
			if p.Auth {
				// auth requested but no upstream configured — leave a visible note
				// rather than silently serving the service unprotected.
				sb.WriteString("\t# WARNING: auth requested but auth_upstream is unset; service is UNPROTECTED\n")
			}
			sb.WriteString(fmt.Sprintf("\treverse_proxy localhost:%d\n", p.Port))
		}

		// Catch upstream-unreachable errors (502/503) so a stopped dev server
		// gets a readable message instead of a blank/hung response. App-level
		// 4xx/5xx pass through untouched.
		sb.WriteString("\thandle_errors 502 503 {\n")
		sb.WriteString(fmt.Sprintf("\t\trespond \"%s is not running (port %d) — error {err.status_code}\" 503\n", p.Name, p.Port))
		sb.WriteString("\t}\n")

		sb.WriteString("}\n\n")
	}

	return sb.String()
}

func Write(cfg *config.Config, content string) error {
	// Ensure directory exists
	dir := filepath.Dir(cfg.CaddyfilePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	return os.WriteFile(cfg.CaddyfilePath, []byte(content), 0644)
}
