package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"dev-router/internal/config"
	"dev-router/internal/scanner"
)

func Generate(cfg *config.Config, projects []scanner.Project) string {
	var sb strings.Builder

	sb.WriteString("# Generated by dev-router - do not edit manually\n\n")

	for _, p := range projects {
		if !p.Enabled {
			continue
		}

		subdomain := fmt.Sprintf("%s.%s", p.Name, cfg.Domain)

		sb.WriteString(fmt.Sprintf("%s {\n", subdomain))
		sb.WriteString(fmt.Sprintf("\ttls %s %s\n", cfg.CertPath, cfg.KeyPath))
		sb.WriteString(fmt.Sprintf("\treverse_proxy localhost:%d\n", p.Port))
		sb.WriteString("}\n\n")
	}

	return sb.String()
}

func Write(cfg *config.Config, content string) error {
	// Ensure directory exists
	dir := filepath.Dir(cfg.CaddyfilePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	return os.WriteFile(cfg.CaddyfilePath, []byte(content), 0644)
}
