package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mikiobraun/dev-router/internal/config"
	"github.com/mikiobraun/dev-router/internal/scanner"
)

// Preflight defaults. Broad enough for the REST data plane (GET + future
// PUT/POST/DELETE, If-Match for optimistic concurrency) and the OAuth fetches
// (Authorization, JSON bodies).
const (
	corsMethods = "GET, PUT, POST, DELETE, OPTIONS"
	corsHeaders = "Authorization, Content-Type, If-Match"
	corsMaxAge  = "600"
)

func Generate(cfg *config.Config, projects []scanner.Project) string {
	var sb strings.Builder

	sb.WriteString("# Generated by dev-router - do not edit manually\n\n")

	for _, p := range projects {
		if !p.Enabled {
			continue
		}

		// The standard, generated vhost — skipped for import-only projects
		// (no port), which bring their own site blocks via caddy_import.
		if p.Port > 0 {
			host := hostname(cfg, p)
			sb.WriteString(fmt.Sprintf("%s {\n", host))
			if cfg.CertPath != "" && cfg.KeyPath != "" {
				sb.WriteString(fmt.Sprintf("\ttls %s %s\n", cfg.CertPath, cfg.KeyPath))
			}

			if len(p.CORSOrigins) > 0 {
				// Wrap the CORS preamble + routing in a route{} so ordering is
				// explicit: the preflight is answered before forward_auth, and the
				// deferred CORS headers land on every response — including the 401
				// the SPA must be able to read to discover the auth server.
				sb.WriteString("\troute {\n")
				sb.WriteString(corsPreamble(p, "\t\t"))
				sb.WriteString(serviceHandlers(cfg, p, "\t\t"))
				sb.WriteString("\t}\n")
			} else {
				sb.WriteString(serviceHandlers(cfg, p, "\t"))
			}

			// Catch upstream-unreachable errors (502/503) so a stopped dev server
			// gets a readable message instead of a blank/hung response. App-level
			// 4xx/5xx pass through untouched.
			sb.WriteString("\thandle_errors 502 503 {\n")
			sb.WriteString(fmt.Sprintf("\t\trespond \"%s is not running (%s) — error {err.status_code}\" 503\n", p.Name, upstream(p)))
			sb.WriteString("\t}\n")

			sb.WriteString("}\n\n")
		}

		// Escape hatch: pull in the project's own raw Caddy snippet verbatim.
		// dev-router doesn't parse or validate it — the project owns its hosts,
		// ports, and correctness. Caddy validates it at load time.
		if p.CaddyImport != "" {
			sb.WriteString(fmt.Sprintf("# %s: project-owned Caddy snippet (caddy_import escape hatch)\n", p.Name))
			sb.WriteString(fmt.Sprintf("import %s\n\n", p.CaddyImport))
		}
	}

	return sb.String()
}

// serviceHandlers emits the routing handlers for a project at the given indent:
// the forward_auth-gated pair when auth is on (and an upstream is set), or a
// plain reverse_proxy otherwise.
func serviceHandlers(cfg *config.Config, p scanner.Project, ind string) string {
	var sb strings.Builder

	if p.Auth && cfg.AuthUpstream != "" {
		// OAuth discovery must be public (not gated), and it identifies the
		// resource by this host — route it to the auth service.
		sb.WriteString(ind + "handle /.well-known/oauth-protected-resource {\n")
		sb.WriteString(ind + "\treverse_proxy " + cfg.AuthUpstream + "\n")
		sb.WriteString(ind + "}\n")
		// Everything else is gated: forward_auth validates, then we proxy.
		sb.WriteString(ind + "handle {\n")
		sb.WriteString(ind + "\tforward_auth " + cfg.AuthUpstream + " {\n")
		sb.WriteString(ind + "\t\turi /verify\n")
		sb.WriteString(ind + "\t\tcopy_headers X-Volume-User X-Volume-Scopes\n")
		sb.WriteString(ind + "\t}\n")
		sb.WriteString(backendProxy(p, ind+"\t"))
		sb.WriteString(ind + "}\n")
		return sb.String()
	}

	if p.Auth {
		// auth requested but no upstream configured — leave a visible note
		// rather than silently serving the service unprotected.
		sb.WriteString(ind + "# WARNING: auth requested but auth_upstream is unset; service is UNPROTECTED\n")
	}
	sb.WriteString(backendProxy(p, ind))
	return sb.String()
}

// backendProxy emits the reverse_proxy to the service's localhost port, adding a
// Caddy-injected shared bearer when the project set `token`. The token value is
// referenced from Caddy's environment ({env.<NAME>}) and never embedded here;
// it replaces the client's Authorization (already consumed by forward_auth) so
// the backend sees only the gateway token.
// upstream returns the host:port for a project's reverse_proxy target.
func upstream(p scanner.Project) string {
	host := p.Host
	if host == "" {
		host = "localhost"
	}
	return fmt.Sprintf("%s:%d", host, p.Port)
}

func backendProxy(p scanner.Project, ind string) string {
	line := fmt.Sprintf("%sreverse_proxy %s", ind, upstream(p))
	if !p.Token {
		return line + "\n"
	}
	var sb strings.Builder
	sb.WriteString(line + " {\n")
	sb.WriteString(ind + "\theader_up Authorization \"Bearer {env." + tokenEnvName(p) + "}\"\n")
	sb.WriteString(ind + "}\n")
	return sb.String()
}

// tokenEnvName is the Caddy env var that holds the shared bearer: TokenEnv if
// set, else <NAME>_TOKEN with the name upper-cased and non-alphanumerics as '_'
// (so "volume-auth" → VOLUME_AUTH_TOKEN).
func tokenEnvName(p scanner.Project) string {
	if p.TokenEnv != "" {
		return p.TokenEnv
	}
	var b strings.Builder
	for _, r := range strings.ToUpper(p.Name) {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	b.WriteString("_TOKEN")
	return b.String()
}

// corsPreamble emits, at the given indent: the response CORS headers (reflecting
// each allowlisted origin, or "*"), deferred so they apply to proxied and error
// responses alike; and a preflight handler that answers OPTIONS with 204 before
// any auth check runs.
func corsPreamble(p scanner.Project, ind string) string {
	var sb strings.Builder

	writeHeaderBody := func(origin string) {
		sb.WriteString(ind + "\tAccess-Control-Allow-Origin " + quote(origin) + "\n")
		if len(p.CORSExpose) > 0 {
			sb.WriteString(ind + "\tAccess-Control-Expose-Headers " + quote(strings.Join(p.CORSExpose, ", ")) + "\n")
		}
		sb.WriteString(ind + "\tVary Origin\n")
		sb.WriteString(ind + "\tdefer\n")
	}

	if len(p.CORSOrigins) == 1 && p.CORSOrigins[0] == "*" {
		sb.WriteString(ind + "header {\n")
		writeHeaderBody("*")
		sb.WriteString(ind + "}\n")
	} else {
		// Reflect only allowlisted origins, so the browser sees ACAO for its own
		// origin and nothing for others.
		for i, o := range p.CORSOrigins {
			m := fmt.Sprintf("@cors_o%d", i)
			sb.WriteString(fmt.Sprintf("%s%s header Origin %s\n", ind, m, o))
			sb.WriteString(fmt.Sprintf("%sheader %s {\n", ind, m))
			writeHeaderBody(o)
			sb.WriteString(ind + "}\n")
		}
	}

	// Preflight: answered before the gated handlers. ACAO/Expose/Vary come from
	// the deferred header above (the Origin is present on the OPTIONS too).
	sb.WriteString(ind + "@preflight method OPTIONS\n")
	sb.WriteString(ind + "handle @preflight {\n")
	sb.WriteString(ind + "\theader Access-Control-Allow-Methods " + quote(corsMethods) + "\n")
	sb.WriteString(ind + "\theader Access-Control-Allow-Headers " + quote(corsHeaders) + "\n")
	sb.WriteString(ind + "\theader Access-Control-Max-Age " + quote(corsMaxAge) + "\n")
	sb.WriteString(ind + "\trespond 204\n")
	sb.WriteString(ind + "}\n")
	return sb.String()
}

// hostname returns the Caddy site address for a project: the project's own
// domain override if set, otherwise {name}.{global_domain}.
func hostname(cfg *config.Config, p scanner.Project) string {
	if p.Domain != "" {
		return p.Domain
	}
	return fmt.Sprintf("%s.%s", p.Name, cfg.Domain)
}

func quote(s string) string { return "\"" + s + "\"" }

func Write(cfg *config.Config, content string) error {
	// Ensure directory exists
	dir := filepath.Dir(cfg.CaddyfilePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	return os.WriteFile(cfg.CaddyfilePath, []byte(content), 0644)
}
